/**
 * Theme block transcribed verbatim from the Stitch export (via
 * ../reference/cine-journal/_build/tailwind.config.js) so the React app renders
 * with byte-identical design tokens. Only `content` differs — it now scans JSX
 * instead of the four static HTML files.
 */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#e3e6ff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#fcf9f8",
        outline: "#737688",
        error: "#ba1a1a",
        "surface-container": "#f0eded",
        "surface-variant": "#e5e2e1",
        "secondary-container": "#e2241f",
        "surface-container-highest": "#e5e2e1",
        "on-surface-variant": "#434656",
        "surface-container-high": "#eae7e7",
        "tertiary-container": "#c13301",
        "surface-tint": "#004dea",
        "secondary-fixed": "#ffdad5",
        "inverse-primary": "#b6c4ff",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "on-tertiary-fixed": "#3b0900",
        "on-secondary-fixed-variant": "#930005",
        "on-primary-fixed-variant": "#0039b3",
        "surface-container-lowest": "#ffffff",
        tertiary: "#972500",
        "primary-fixed-dim": "#b6c4ff",
        "on-secondary-container": "#fffbff",
        "on-tertiary-container": "#ffe1d9",
        "on-background": "#1c1b1b",
        secondary: "#bc000a",
        "on-primary": "#ffffff",
        "outline-variant": "#c3c5d9",
        "primary-fixed": "#dce1ff",
        "primary-container": "#0055ff",
        "tertiary-fixed": "#ffdbd1",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#ffb4aa",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "on-secondary-fixed": "#410001",
        surface: "#fcf9f8",
        "on-primary-fixed": "#001551",
        "inverse-surface": "#313030",
        primary: "#0041c8",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f3f0ef",
        "tertiary-fixed-dim": "#ffb5a0",
        "on-tertiary-fixed-variant": "#872100",
        "on-surface": "#1c1b1b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xxl: "80px",
        xs: "4px",
        "margin-desktop": "64px",
        lg: "24px",
        "margin-mobile": "16px",
        unit: "4px",
        xl: "48px",
        gutter: "24px",
        md: "16px",
        sm: "8px",
      },
      fontFamily: {
        "body-md": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "label-sm": ["JetBrains Mono"],
        "display-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
